version: '2.1'
orbs:
  provar: provartesting/provar@2.6.1
jobs:
  build:
    executor:
      name: provar/default
      tag: 8-jdk-stretch-node-browsers
    parameters:
      build_file:
        default: build.xml
        type: string
      environment:
        default: Dev
        type: string
      project_name:
        default: DemoProject
        type: string
      test_plan:
        default: Regression
        type: string
    steps:
      - checkout
      - provar/setup_provar
      - run:
          command: >-
            ant -Dprovar.home="/home/circleci/project/Provar_Home"
            -Dproject.home="/home/circleci/project/<< parameters.project_name
            >>" -Dtest.plan="<< parameters.test_plan >>" -Denvironment="<<
            parameters.environment >>" -Demail.target=<< parameters.email_target
            >> -f << parameters.project_name >>/ANT/<< parameters.build_file >>
          name: Run Provar Tests
      - store_test_results:
          path: << parameters.project_name >>/ANT/Results/JUnit html/
workflows: null
